name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential postgresql-server-dev-16

      - name: Install clang-19
        run: |
          sudo apt-get install -y clang-19

      - name: Build extension
        run: |
          make
